from __future__ import annotations

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.db.session import SessionLocal
from app.gifts.models import GiftItem


SEED_GIFTS: list[dict] = [
    {
        "name": "감성 북마크 세트",
        "category": "문구/독서",
        "description": "독서 시간을 더 특별하게 만드는 금속 북마크와 짧은 메시지 카드 세트",
        "min_price": 12000,
        "max_price": 28000,
        "tags_json": ["독서", "문구", "감성", "부담없는", "미니멀"],
        "suitable_relations_json": ["친구", "동료", "선생님"],
        "suitable_occasions_json": ["생일", "감사", "응원", "가벼운 선물"],
        "suitable_personality_json": ["감성적인", "차분한", "꼼꼼한", "미니멀한"],
    },
    {
        "name": "프리미엄 드립백 커피 박스",
        "category": "디저트/간식",
        "description": "집이나 사무실에서 간편하게 즐기는 다양한 산지의 드립백 커피 구성",
        "min_price": 25000,
        "max_price": 45000,
        "tags_json": ["카페/디저트", "커피", "실용", "센스있는", "부담없는"],
        "suitable_relations_json": ["친구", "동료", "가족", "선생님"],
        "suitable_occasions_json": ["생일", "감사", "응원", "가벼운 선물"],
        "suitable_personality_json": ["차분한", "실용적인", "미니멀한"],
    },
    {
        "name": "수제 쿠키 앤 티 세트",
        "category": "디저트/간식",
        "description": "수제 쿠키와 허브티를 함께 담은 따뜻한 분위기의 선물 세트",
        "min_price": 30000,
        "max_price": 48000,
        "tags_json": ["카페/디저트", "디저트", "감성", "귀여운", "센스있는"],
        "suitable_relations_json": ["친구", "연인", "가족", "동료"],
        "suitable_occasions_json": ["생일", "기념일", "감사", "응원"],
        "suitable_personality_json": ["감성적인", "귀여운 것을 좋아하는", "차분한"],
    },
    {
        "name": "미니 향수 디스커버리 키트",
        "category": "뷰티/향기",
        "description": "여러 향을 부담 없이 시향할 수 있는 미니 향수 키트",
        "min_price": 35000,
        "max_price": 50000,
        "tags_json": ["뷰티", "향기", "트렌디", "센스있는", "고급스러운"],
        "suitable_relations_json": ["친구", "연인"],
        "suitable_occasions_json": ["생일", "기념일", "축하"],
        "suitable_personality_json": ["감성적인", "트렌디한", "새로운 경험을 좋아하는"],
    },
    {
        "name": "감성 무드등",
        "category": "홈/인테리어",
        "description": "침대 옆이나 책상 위에 두기 좋은 은은한 빛의 작은 무드등",
        "min_price": 28000,
        "max_price": 48000,
        "tags_json": ["인테리어", "감성", "홈", "센스있는", "미니멀"],
        "suitable_relations_json": ["친구", "연인", "가족"],
        "suitable_occasions_json": ["생일", "집들이", "기념일", "응원"],
        "suitable_personality_json": ["감성적인", "차분한", "미니멀한"],
    },
    {
        "name": "독서 노트 패키지",
        "category": "문구/독서",
        "description": "읽은 책을 기록하기 좋은 독서 노트와 펜 세트",
        "min_price": 18000,
        "max_price": 36000,
        "tags_json": ["독서", "문구", "기록", "실용", "감성"],
        "suitable_relations_json": ["친구", "동료", "선생님"],
        "suitable_occasions_json": ["생일", "응원", "감사"],
        "suitable_personality_json": ["차분한", "꼼꼼한", "감성적인"],
    },
    {
        "name": "카페 디저트 모바일 교환권",
        "category": "디저트/간식",
        "description": "상대가 원하는 날 사용할 수 있는 카페 디저트 교환권",
        "min_price": 10000,
        "max_price": 30000,
        "tags_json": ["카페/디저트", "디저트", "실용", "부담없는"],
        "suitable_relations_json": ["친구", "동료", "기타"],
        "suitable_occasions_json": ["가벼운 선물", "생일", "응원", "감사"],
        "suitable_personality_json": ["실용적인", "활동적인", "상관없음"],
    },
    {
        "name": "데스크 정리 트레이",
        "category": "홈/인테리어",
        "description": "책상 위 작은 물건을 깔끔하게 정리하는 미니 트레이",
        "min_price": 18000,
        "max_price": 42000,
        "tags_json": ["인테리어", "문구", "실용", "미니멀"],
        "suitable_relations_json": ["친구", "동료", "가족"],
        "suitable_occasions_json": ["생일", "응원", "집들이", "가벼운 선물"],
        "suitable_personality_json": ["꼼꼼한", "실용적인", "미니멀한"],
    },
    {
        "name": "핸드크림 트리오",
        "category": "뷰티/향기",
        "description": "계절에 상관없이 쓰기 좋은 향별 핸드크림 3종 세트",
        "min_price": 22000,
        "max_price": 42000,
        "tags_json": ["뷰티", "향기", "실용", "부담없는"],
        "suitable_relations_json": ["친구", "동료", "가족", "선생님"],
        "suitable_occasions_json": ["생일", "감사", "가벼운 선물"],
        "suitable_personality_json": ["실용적인", "감성적인", "차분한"],
    },
    {
        "name": "블루투스 스마트 태그",
        "category": "테크/가젯",
        "description": "가방이나 열쇠에 달아 분실을 줄여주는 작은 스마트 태그",
        "min_price": 30000,
        "max_price": 49000,
        "tags_json": ["테크", "가젯", "실용", "센스있는"],
        "suitable_relations_json": ["친구", "가족", "동료"],
        "suitable_occasions_json": ["생일", "축하", "응원"],
        "suitable_personality_json": ["실용적인", "꼼꼼한", "트렌디한"],
    },
    {
        "name": "홈카페 유리컵 세트",
        "category": "홈/인테리어",
        "description": "아이스 커피와 디저트를 담기 좋은 디자인 유리컵 세트",
        "min_price": 26000,
        "max_price": 47000,
        "tags_json": ["카페/디저트", "인테리어", "홈", "감성", "센스있는"],
        "suitable_relations_json": ["친구", "연인", "가족"],
        "suitable_occasions_json": ["생일", "집들이", "기념일"],
        "suitable_personality_json": ["감성적인", "트렌디한", "미니멀한"],
    },
    {
        "name": "무선 충전 패드",
        "category": "테크/가젯",
        "description": "책상이나 침대 옆에 두기 좋은 깔끔한 무선 충전 패드",
        "min_price": 25000,
        "max_price": 50000,
        "tags_json": ["테크", "실용", "미니멀", "가젯"],
        "suitable_relations_json": ["친구", "동료", "가족"],
        "suitable_occasions_json": ["생일", "축하", "응원"],
        "suitable_personality_json": ["실용적인", "미니멀한", "꼼꼼한"],
    },
    {
        "name": "아로마 룸스프레이",
        "category": "뷰티/향기",
        "description": "방과 침구에 가볍게 뿌리기 좋은 편안한 향의 룸스프레이",
        "min_price": 18000,
        "max_price": 38000,
        "tags_json": ["향기", "인테리어", "감성", "차분한"],
        "suitable_relations_json": ["친구", "연인", "가족"],
        "suitable_occasions_json": ["생일", "집들이", "응원", "감사"],
        "suitable_personality_json": ["감성적인", "차분한", "미니멀한"],
    },
    {
        "name": "요가 스트레칭 밴드 세트",
        "category": "건강/운동",
        "description": "가볍게 홈트와 스트레칭을 시작하기 좋은 밴드 구성",
        "min_price": 15000,
        "max_price": 35000,
        "tags_json": ["운동", "건강", "실용", "응원"],
        "suitable_relations_json": ["친구", "가족", "동료"],
        "suitable_occasions_json": ["응원", "생일", "축하"],
        "suitable_personality_json": ["활동적인", "실용적인", "새로운 경험을 좋아하는"],
    },
    {
        "name": "러닝 양말 패키지",
        "category": "건강/운동",
        "description": "운동을 즐기는 사람에게 부담 없이 좋은 기능성 양말 세트",
        "min_price": 12000,
        "max_price": 32000,
        "tags_json": ["운동", "건강", "실용", "부담없는"],
        "suitable_relations_json": ["친구", "동료", "가족"],
        "suitable_occasions_json": ["응원", "가벼운 선물", "생일"],
        "suitable_personality_json": ["활동적인", "실용적인"],
    },
    {
        "name": "미니 보드게임",
        "category": "취미용품",
        "description": "친구들과 짧은 시간 즐기기 좋은 휴대용 보드게임",
        "min_price": 18000,
        "max_price": 38000,
        "tags_json": ["게임", "취미", "귀여운", "새로운 경험"],
        "suitable_relations_json": ["친구", "연인", "가족"],
        "suitable_occasions_json": ["생일", "축하", "가벼운 선물"],
        "suitable_personality_json": ["활동적인", "새로운 경험을 좋아하는", "귀여운 것을 좋아하는"],
    },
    {
        "name": "여행용 파우치 세트",
        "category": "패션소품",
        "description": "여행 짐을 깔끔하게 나누어 담을 수 있는 파우치 구성",
        "min_price": 20000,
        "max_price": 42000,
        "tags_json": ["여행", "실용", "정리", "미니멀"],
        "suitable_relations_json": ["친구", "가족", "동료"],
        "suitable_occasions_json": ["생일", "응원", "축하"],
        "suitable_personality_json": ["실용적인", "꼼꼼한", "활동적인"],
    },
    {
        "name": "패브릭 북커버",
        "category": "문구/독서",
        "description": "책을 보호하고 독서 취향을 드러낼 수 있는 패브릭 북커버",
        "min_price": 16000,
        "max_price": 34000,
        "tags_json": ["독서", "문구", "감성", "귀여운", "미니멀"],
        "suitable_relations_json": ["친구", "연인", "동료"],
        "suitable_occasions_json": ["생일", "응원", "가벼운 선물"],
        "suitable_personality_json": ["감성적인", "차분한", "귀여운 것을 좋아하는"],
    },
    {
        "name": "프리미엄 초콜릿 컬렉션",
        "category": "디저트/간식",
        "description": "작지만 고급스럽게 마음을 전하기 좋은 초콜릿 컬렉션",
        "min_price": 32000,
        "max_price": 55000,
        "tags_json": ["디저트", "고급스러운", "감성", "기념일"],
        "suitable_relations_json": ["연인", "친구", "가족"],
        "suitable_occasions_json": ["기념일", "생일", "감사", "축하"],
        "suitable_personality_json": ["감성적인", "트렌디한"],
    },
    {
        "name": "디자인 머그컵",
        "category": "홈/인테리어",
        "description": "매일 쓰기 좋은 포인트 디자인의 머그컵",
        "min_price": 15000,
        "max_price": 33000,
        "tags_json": ["카페/디저트", "홈", "실용", "귀여운", "부담없는"],
        "suitable_relations_json": ["친구", "동료", "가족", "선생님"],
        "suitable_occasions_json": ["생일", "감사", "집들이", "가벼운 선물"],
        "suitable_personality_json": ["실용적인", "귀여운 것을 좋아하는", "감성적인"],
    },
    {
        "name": "캔들 워머 미니 세트",
        "category": "홈/인테리어",
        "description": "불 없이 향초를 은은하게 즐길 수 있는 미니 워머와 캔들 세트",
        "min_price": 45000,
        "max_price": 85000,
        "tags_json": ["향기", "인테리어", "감성", "고급스러운"],
        "suitable_relations_json": ["연인", "친구", "가족"],
        "suitable_occasions_json": ["생일", "기념일", "집들이"],
        "suitable_personality_json": ["감성적인", "차분한", "미니멀한"],
    },
    {
        "name": "가죽 카드지갑",
        "category": "패션소품",
        "description": "깔끔한 디자인으로 오래 쓰기 좋은 카드지갑",
        "min_price": 50000,
        "max_price": 95000,
        "tags_json": ["패션", "실용", "고급스러운", "미니멀"],
        "suitable_relations_json": ["연인", "가족", "친구"],
        "suitable_occasions_json": ["생일", "기념일", "축하"],
        "suitable_personality_json": ["실용적인", "미니멀한", "트렌디한"],
    },
    {
        "name": "무선 이어폰 케이스",
        "category": "패션소품",
        "description": "무선 이어폰에 포인트를 주는 귀여운 보호 케이스",
        "min_price": 9000,
        "max_price": 25000,
        "tags_json": ["테크", "패션", "귀여운", "부담없는"],
        "suitable_relations_json": ["친구", "동료", "기타"],
        "suitable_occasions_json": ["가벼운 선물", "생일", "응원"],
        "suitable_personality_json": ["귀여운 것을 좋아하는", "트렌디한"],
    },
    {
        "name": "필사 문장 카드 세트",
        "category": "문구/독서",
        "description": "좋은 문장을 따라 쓰며 마음을 정리할 수 있는 카드와 펜 세트",
        "min_price": 14000,
        "max_price": 30000,
        "tags_json": ["독서", "문구", "감성", "응원"],
        "suitable_relations_json": ["친구", "선생님", "동료"],
        "suitable_occasions_json": ["응원", "감사", "생일"],
        "suitable_personality_json": ["감성적인", "차분한", "꼼꼼한"],
    },
    {
        "name": "티 코스터 세트",
        "category": "홈/인테리어",
        "description": "홈카페 분위기를 살려주는 디자인 코스터 구성",
        "min_price": 12000,
        "max_price": 28000,
        "tags_json": ["카페/디저트", "인테리어", "홈", "부담없는"],
        "suitable_relations_json": ["친구", "동료", "가족"],
        "suitable_occasions_json": ["집들이", "생일", "가벼운 선물"],
        "suitable_personality_json": ["감성적인", "미니멀한", "실용적인"],
    },
    {
        "name": "퍼즐 포스터 키트",
        "category": "취미용품",
        "description": "완성 후 포스터처럼 걸 수 있는 감성 일러스트 퍼즐",
        "min_price": 24000,
        "max_price": 46000,
        "tags_json": ["취미", "인테리어", "감성", "새로운 경험"],
        "suitable_relations_json": ["친구", "연인", "가족"],
        "suitable_occasions_json": ["생일", "기념일", "응원"],
        "suitable_personality_json": ["차분한", "감성적인", "새로운 경험을 좋아하는"],
    },
    {
        "name": "저자극 립밤 세트",
        "category": "뷰티/향기",
        "description": "계절마다 유용한 저자극 립밤 2~3종 구성",
        "min_price": 12000,
        "max_price": 26000,
        "tags_json": ["뷰티", "실용", "부담없는"],
        "suitable_relations_json": ["친구", "가족", "동료"],
        "suitable_occasions_json": ["가벼운 선물", "감사", "생일"],
        "suitable_personality_json": ["실용적인", "차분한"],
    },
    {
        "name": "휴대용 마사지볼",
        "category": "건강/운동",
        "description": "목과 어깨를 가볍게 풀어주는 휴대용 마사지볼",
        "min_price": 10000,
        "max_price": 24000,
        "tags_json": ["건강", "운동", "실용", "응원"],
        "suitable_relations_json": ["가족", "동료", "친구"],
        "suitable_occasions_json": ["응원", "감사", "가벼운 선물"],
        "suitable_personality_json": ["실용적인", "활동적인"],
    },
    {
        "name": "감사 메시지 플라워 박스",
        "category": "홈/인테리어",
        "description": "보존화와 메시지 카드를 함께 담은 작은 플라워 박스",
        "min_price": 38000,
        "max_price": 70000,
        "tags_json": ["감성", "꽃", "감동적인", "고급스러운"],
        "suitable_relations_json": ["가족", "선생님", "연인", "친구"],
        "suitable_occasions_json": ["감사", "기념일", "생일", "축하"],
        "suitable_personality_json": ["감성적인", "차분한"],
    },
    {
        "name": "반려동물 장난감 세트",
        "category": "취미용품",
        "description": "반려동물과 함께 즐길 수 있는 귀여운 장난감 구성",
        "min_price": 15000,
        "max_price": 35000,
        "tags_json": ["반려동물", "귀여운", "취미", "부담없는"],
        "suitable_relations_json": ["친구", "가족", "동료"],
        "suitable_occasions_json": ["생일", "가벼운 선물", "응원"],
        "suitable_personality_json": ["귀여운 것을 좋아하는", "활동적인"],
    },
    {
        "name": "프리미엄 견과 선물세트",
        "category": "디저트/간식",
        "description": "건강을 챙기는 마음을 담기 좋은 견과류 선물세트",
        "min_price": 30000,
        "max_price": 60000,
        "tags_json": ["건강", "디저트", "실용", "고급스러운"],
        "suitable_relations_json": ["가족", "선생님", "동료"],
        "suitable_occasions_json": ["감사", "생일", "축하"],
        "suitable_personality_json": ["실용적인", "차분한"],
    },
    {
        "name": "DIY 미니 가드닝 키트",
        "category": "취미용품",
        "description": "작은 화분을 직접 키워보는 초보자용 가드닝 키트",
        "min_price": 18000,
        "max_price": 40000,
        "tags_json": ["취미", "인테리어", "새로운 경험", "감성"],
        "suitable_relations_json": ["친구", "가족", "연인"],
        "suitable_occasions_json": ["생일", "집들이", "응원"],
        "suitable_personality_json": ["새로운 경험을 좋아하는", "차분한", "감성적인"],
    },
    {
        "name": "음악 플레이리스트 카드",
        "category": "문구/독서",
        "description": "QR 플레이리스트와 메시지를 함께 담는 감성 카드 세트",
        "min_price": 9000,
        "max_price": 22000,
        "tags_json": ["음악", "감성", "문구", "부담없는"],
        "suitable_relations_json": ["친구", "연인"],
        "suitable_occasions_json": ["생일", "기념일", "응원", "가벼운 선물"],
        "suitable_personality_json": ["감성적인", "트렌디한", "귀여운 것을 좋아하는"],
    },
    {
        "name": "영화관람권 세트",
        "category": "취미용품",
        "description": "좋아하는 영화를 직접 고를 수 있는 영화 관람권",
        "min_price": 28000,
        "max_price": 50000,
        "tags_json": ["영화/드라마", "경험", "실용", "센스있는"],
        "suitable_relations_json": ["친구", "연인", "가족"],
        "suitable_occasions_json": ["생일", "기념일", "축하"],
        "suitable_personality_json": ["활동적인", "새로운 경험을 좋아하는", "실용적인"],
    },
    {
        "name": "고급 볼펜 세트",
        "category": "문구/독서",
        "description": "업무와 기록에 모두 어울리는 깔끔한 볼펜 세트",
        "min_price": 30000,
        "max_price": 65000,
        "tags_json": ["문구", "실용", "고급스러운", "미니멀"],
        "suitable_relations_json": ["동료", "선생님", "가족", "친구"],
        "suitable_occasions_json": ["감사", "축하", "생일"],
        "suitable_personality_json": ["꼼꼼한", "실용적인", "미니멀한"],
    },
    {
        "name": "귀여운 키링 세트",
        "category": "패션소품",
        "description": "가방이나 파우치에 달기 좋은 작은 키링 세트",
        "min_price": 8000,
        "max_price": 20000,
        "tags_json": ["귀여운", "패션", "부담없는"],
        "suitable_relations_json": ["친구", "동료", "기타"],
        "suitable_occasions_json": ["가벼운 선물", "생일", "응원"],
        "suitable_personality_json": ["귀여운 것을 좋아하는", "트렌디한"],
    },
    {
        "name": "프리미엄 샤워 오일",
        "category": "뷰티/향기",
        "description": "하루 끝 휴식 시간을 챙겨주는 향 좋은 샤워 오일",
        "min_price": 42000,
        "max_price": 80000,
        "tags_json": ["뷰티", "향기", "고급스러운", "감동적인"],
        "suitable_relations_json": ["연인", "친구", "가족"],
        "suitable_occasions_json": ["생일", "기념일", "감사"],
        "suitable_personality_json": ["감성적인", "차분한", "트렌디한"],
    },
]


def seed_gifts(db: Session) -> int:
    inserted_or_updated = 0
    for payload in SEED_GIFTS:
        gift = db.execute(select(GiftItem).where(GiftItem.name == payload["name"])).scalar_one_or_none()
        if gift is None:
            gift = GiftItem(**payload)
            db.add(gift)
        else:
            for key, value in payload.items():
                setattr(gift, key, value)
            gift.active = True
        inserted_or_updated += 1
    db.commit()
    return inserted_or_updated


def main() -> None:
    with SessionLocal() as db:
        count = seed_gifts(db)
    print(f"Seeded {count} gift items")


if __name__ == "__main__":
    main()
